// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPaQe0Gy7Ne6dfb3dtAm48JIDtkdPgNWA',
    appId: '1:225963577293:web:76faeec4602bc6a80b3e84',
    messagingSenderId: '225963577293',
    projectId: 'chord-everdu',
    authDomain: 'chord-everdu.firebaseapp.com',
    storageBucket: 'chord-everdu.appspot.com',
    measurementId: 'G-KRHDNH1YZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrwwK-CdP8-DmLuiIfvnuKqwQW0IaZuSY',
    appId: '1:225963577293:android:ba061317877232580b3e84',
    messagingSenderId: '225963577293',
    projectId: 'chord-everdu',
    storageBucket: 'chord-everdu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDheuAc5AzHeG_SXEqefcvRRdLygvwO_uU',
    appId: '1:225963577293:ios:57c99d1210c861f70b3e84',
    messagingSenderId: '225963577293',
    projectId: 'chord-everdu',
    storageBucket: 'chord-everdu.appspot.com',
    androidClientId: '225963577293-fn321hnf51250sqt6jt0ba2bcr82pp5l.apps.googleusercontent.com',
    iosClientId: '225963577293-ursg0us5jsa9sbtob3l3rpt65hmbsuc8.apps.googleusercontent.com',
    iosBundleId: 'com.everdu.chordEverdu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDheuAc5AzHeG_SXEqefcvRRdLygvwO_uU',
    appId: '1:225963577293:ios:744b429161ea67410b3e84',
    messagingSenderId: '225963577293',
    projectId: 'chord-everdu',
    storageBucket: 'chord-everdu.appspot.com',
    androidClientId: '225963577293-fn321hnf51250sqt6jt0ba2bcr82pp5l.apps.googleusercontent.com',
    iosClientId: '225963577293-gelt2rpoigdot365ofjmidbdhit57onq.apps.googleusercontent.com',
    iosBundleId: 'com.everdu.chordEverdu.RunnerTests',
  );
}
