name: Android Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run Unit Test
        run: flutter test
      - name: Start release build
        run: flutter build appbundle
